export const featuredProjects = [
  {
    title: 'E-commerce Platform',
    slug: 'e-commerce-platform',
    description: 'A high-performance modern store with real-time cart, product filters, and fluid checkout animations.',
    category: 'React',
    tags: ['React 19', 'Vite', 'CSS Grid', 'REST API'],
    featured: true,
    github: 'https://github.com/rohitghorai/ecommerce-platform',
    liveUrl: '/projects/e-commerce-platform',
    stats: { speed: '99ms', products: '2,400+', rating: '4.9/5' },
    details:
      'Built a fast, responsive shopping experience with React and modern UI patterns. Includes product listings, dynamic search filtering, cart drawer flows, and instant checkout simulation with micro-interactions.',
  },
  {
    title: 'Admin Dashboard',
    slug: 'admin-dashboard',
    description: 'Real-time analytics dashboard with interactive data visualization, user management, and KPI tracking.',
    category: 'JavaScript',
    tags: ['JavaScript ES6+', 'DataViz', 'Glassmorphism', 'Charts'],
    featured: true,
    github: 'https://github.com/rohitghorai/admin-dashboard',
    liveUrl: '/projects/admin-dashboard',
    stats: { users: '18.2k', uptime: '99.9%', latency: '24ms' },
    details:
      'Developed a clean, high-contrast dashboard for tracking business metrics, user engagement, and revenue analytics. Features custom CSS progress bars, interactive KPI cards, and responsive table views.',
  },
  {
    title: 'Portfolio Website',
    slug: 'portfolio-website',
    description: 'Personal portfolio featuring interactive Three.js 3D graphics, anime.js motion, and glassmorphism styling.',
    category: 'UI/UX',
    tags: ['Three.js', 'Anime.js', 'React', 'Design System'],
    featured: true,
    github: 'https://github.com/rohitghorai/portfolio',
    liveUrl: '/projects/portfolio-website',
    stats: { fps: '60 FPS', themes: 'Dark/Light', animations: '10+' },
    details:
      'Crafted an immersive personal brand experience with WebGL 3D particle systems, physics-inspired entrance animations, accessible semantic markup, and responsive glassmorphism aesthetic.',
  },
  {
    title: 'Task Planner App',
    slug: 'task-planner-app',
    description: 'Productivity management board with drag-and-drop state, milestone tracking, and priority tagging.',
    category: 'React',
    tags: ['React', 'State Mgmt', 'Vite', 'Productivity'],
    featured: true,
    github: 'https://github.com/rohitghorai/task-planner',
    liveUrl: '/projects/task-planner-app',
    stats: { tasks: 'Unlimited', sync: 'Instant', storage: 'Local' },
    details:
      'Designed a lightweight planner with a clear interface and fast task management flows. Features multi-column kanban boards, category filtering, deadline tracking, and status transitions.',
  },
]

export const allProjects = [
  ...featuredProjects,
  {
    title: 'Weather Forecast App',
    slug: 'weather-forecast-app',
    description: 'Live atmospheric weather forecast dashboard with location search and dynamic dynamic weather visuals.',
    category: 'JavaScript',
    tags: ['JavaScript', 'Fetch API', 'Weather API', 'CSS Motion'],
    featured: false,
    github: 'https://github.com/rohitghorai/weather-app',
    liveUrl: '/projects/weather-forecast-app',
    stats: { cities: '200k+', forecast: '7 Days', precision: 'Hourly' },
    details:
      'Created a live weather dashboard with location-based data and animated visual indicators. Includes hourly forecasts, humidity meters, wind speed gauges, and responsive glass cards.',
  },
  {
    title: 'Chat UI Prototype',
    slug: 'chat-ui-prototype',
    description: 'Modern messaging interface with real-time bubble streams, typing indicators, and mobile-first UX.',
    category: 'UI/UX',
    tags: ['UI/UX', 'Mobile First', 'Figma', 'Component Kit'],
    featured: false,
    github: 'https://github.com/rohitghorai/chat-ui-prototype',
    liveUrl: '/projects/chat-ui-prototype',
    stats: { latency: '<10ms', themes: 'Adaptive', emojis: 'Native' },
    details:
      'Designed a modern conversation interface with clean components and mobile-first layout. Focused on message hierarchy, readability, avatar indicators, and fluid touch interactions.',
  },
  {
    title: 'Learning Management System',
    slug: 'learning-management-system',
    description: 'Content-driven education platform with role-based views, video player cards, and quiz modules.',
    category: 'React',
    tags: ['React', 'Modular CSS', 'E-Learning', 'Router'],
    featured: false,
    github: 'https://github.com/rohitghorai/learning-system',
    liveUrl: '/projects/learning-management-system',
    stats: { courses: '45+', completion: '92%', modules: 'Interactive' },
    details:
      'Built a content-driven education platform with role-based views and interactive lessons. Supports video lecture playback, modular quizzes, and user progress tracking graphs.',
  },
  {
    title: 'Inventory Tracker',
    slug: 'inventory-tracker',
    description: 'Supply management tool for monitoring real-time stock levels, low-quantity alerts, and SKU barcodes.',
    category: 'JavaScript',
    tags: ['JavaScript', 'LocalDB', 'Sorting Algo', 'Tables'],
    featured: false,
    github: 'https://github.com/rohitghorai/inventory-tracker',
    liveUrl: '/projects/inventory-tracker',
    stats: { items: '10,000+', alerts: 'Automated', export: 'CSV/PDF' },
    details:
      'Developed a management tool for monitoring warehouse stock, quantity updates, and product categorisation. Includes instant search, multi-column sorting, and visual status badges.',
  },
  {
    title: 'Travel Booking Landing Page',
    slug: 'travel-booking-landing-page',
    description: 'High-converting travel exploration landing page showcasing destination packages and booking steps.',
    category: 'UI/UX',
    tags: ['UI/UX', 'Landing Page', 'Typography', 'Parallax'],
    featured: false,
    github: 'https://github.com/rohitghorai/travel-booking',
    liveUrl: '/projects/travel-booking-landing-page',
    stats: { destinations: '50+', conversion: '+28%', responsive: '100%' },
    details:
      'Created an immersive landing page focused on conversions and visual storytelling. Highlights trending destinations, itinerary schedules, customer reviews, and clear calls to action.',
  },
  {
    title: 'Fitness Dashboard',
    slug: 'fitness-dashboard',
    description: 'Daily health and workout tracker featuring caloric burn charts, streak counters, and training plans.',
    category: 'React',
    tags: ['React', 'Charts', 'Health Tech', 'Dark Mode'],
    featured: false,
    github: 'https://github.com/rohitghorai/fitness-dashboard',
    liveUrl: '/projects/fitness-dashboard',
    stats: { metrics: '12 KPIs', streaks: 'Gamified', logs: 'Weekly' },
    details:
      'Built a dashboard for daily workout goals, progress charts, and workout planning. Includes animated activity rings, workout log cards, and goal completion celebrations.',
  },
  {
    title: 'Restaurant Website',
    slug: 'restaurant-website',
    description: 'Gastronomy showcase with interactive menu browsing, table reservation module, and chef specials.',
    category: 'UI/UX',
    tags: ['UI/UX', 'Restaurant', 'Reservation Flow', 'Imagery'],
    featured: false,
    github: 'https://github.com/rohitghorai/restaurant-website',
    liveUrl: '/projects/restaurant-website',
    stats: { dishes: '80+', bookings: 'Seamless', ratings: '4.8★' },
    details:
      'Designed a polished culinary restaurant experience showcasing digital menus, interactive dietary filter tags, table booking inquiries, and location maps.',
  },
  {
    title: 'Expense Tracker',
    slug: 'expense-tracker',
    description: 'Financial accounting app with transaction logs, monthly budget caps, and visual expense breakdown.',
    category: 'JavaScript',
    tags: ['JavaScript', 'Budgeting', 'Storage API', 'Charts'],
    featured: false,
    github: 'https://github.com/rohitghorai/expense-tracker',
    liveUrl: '/projects/expense-tracker',
    stats: { currency: 'Multi-FX', export: 'JSON/CSV', security: 'Client-side' },
    details:
      'Implemented a personal finance app with category filtering, recurring expense markers, and clean monthly financial balance calculations.',
  },
]

export const categories = ['All', 'React', 'JavaScript', 'UI/UX']
